name: Merge Release

on:
  release:
    types: [released]

jobs:
  merge-release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    name: Merge release to main

    steps:
    - name: Checkout main branch locally
      uses: actions/checkout@v4
      with:
        ref: main
        fetch-tags: true
        fetch-depth: 0
    - name: Merge tag to local main
      run: |
          git merge ${{ github.event.release.tag_name }}
    - name: Push merge to repository's main branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main


