name: Merge Release

env:
  BRANCH: main

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to merge into'
        required: false
        type: string
        default: ${{ env.BRANCH }}
      tag:
        description: 'Tag to merge'
        required: true
        type: string

jobs:
  merge-release:
    runs-on: ubuntu-latest
    env:
      GIT_USER_EMAIL: "github-actions[bot]@users.noreply.github.com"
      GIT_USER_NAME: "github-actions[bot]"
      BRANCH: ${{ input.branch || env.BRANCH }}
    permissions:
      contents: write
    strategy:
      fail-fast: true

    name: Merge release to ${{ env.branch }}

    steps:
    - name: Checkout ${{ env.branch }} branch locally
      uses: actions/checkout@v4
      with:
        ref: ${{ env.branch }}
        fetch-tags: true
        fetch-depth: 0
    - name: Update git user
      if: ${{ github.actor_id }}
      run: |
        read name email < <(gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /user/$ACCOUNT_ID \
          --jq '.name, .email');

        echo 'GIT_USER_NAME='$name >> $GITHUB_ENV
        echo 'GIT_USER_EMAIL='$email >> $GITHUB_ENV
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ACCOUNT_ID: ${{ github.actor_id }}

    - name: Merge tag to local ${{ env.branch }}
      run: |
          git config --local user.email "$GIT_USER_EMAIL"
          git config --local user.name "$GIT_USER_NAME"
          git merge ${{ inputs.tag || github.event.release.tag_name }}
    - name: Push merge to repository's ${{ env.branch }} branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ env.branch }}


